import type { NewUnitCostLineItem } from "@/types/costing";

type PresetTemplate = Partial<Omit<NewUnitCostLineItem, "section_id" | "unit_id" | "sort_order">>;

export const HARDWARE_PRESETS: PresetTemplate[] = [
  {
    item_name: "Normal Hinge",
    category: "hardware",
    cost_basis: "per_number",
    unit_rate: 65,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Soft-Close Hinge",
    category: "hardware",
    cost_basis: "per_number",
    unit_rate: 150,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Drawer Channel Normal",
    category: "hardware",
    cost_basis: "per_set",
    unit_rate: 350,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Drawer Channel Soft-Close",
    category: "hardware",
    cost_basis: "per_set",
    unit_rate: 650,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Tandem Drawer Channel",
    category: "hardware",
    cost_basis: "per_set",
    unit_rate: 2200,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Sliding Wardrobe Top/Bottom Channel",
    category: "hardware",
    cost_basis: "per_rft",
    unit_rate: 450,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Profile Handle",
    category: "hardware",
    cost_basis: "per_rft",
    unit_rate: 120,
    margin_percentage: 25,
    wastage_percentage: 5,
    include_in_client_price: true,
  },
  {
    item_name: "Gola Profile",
    category: "hardware",
    cost_basis: "per_rft",
    unit_rate: 180,
    margin_percentage: 25,
    wastage_percentage: 5,
    include_in_client_price: true,
  },
  {
    item_name: "Lock",
    category: "hardware",
    cost_basis: "per_number",
    unit_rate: 150,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Tower Bolt",
    category: "hardware",
    cost_basis: "per_number",
    unit_rate: 80,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
];

export const ACCESSORY_PRESETS: PresetTemplate[] = [
  {
    item_name: "Pull-out Basket",
    category: "accessory",
    cost_basis: "per_number",
    unit_rate: 1800,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Laundry Basket",
    category: "accessory",
    cost_basis: "per_number",
    unit_rate: 2500,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Pull-down Hanger",
    category: "accessory",
    cost_basis: "per_number",
    unit_rate: 3500,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Trouser Pull-out",
    category: "accessory",
    cost_basis: "per_number",
    unit_rate: 2200,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Jewellery Tray",
    category: "accessory",
    cost_basis: "per_number",
    unit_rate: 1500,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Mirror Pull-out",
    category: "accessory",
    cost_basis: "per_number",
    unit_rate: 3200,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
];

export const FINISH_PRESETS: PresetTemplate[] = [
  {
    item_name: "Laminate Finish",
    category: "surface_finish",
    cost_basis: "per_sqft",
    unit_rate: 65,
    margin_percentage: 25,
    wastage_percentage: 15,
    include_in_client_price: true,
  },
  {
    item_name: "Duco Finish",
    category: "shutter_finish_vendor",
    cost_basis: "per_sqft",
    unit_rate: 350,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "PU Finish",
    category: "shutter_finish_vendor",
    cost_basis: "per_sqft",
    unit_rate: 450,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Veneer Polish",
    category: "surface_finish",
    cost_basis: "per_sqft",
    unit_rate: 250,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
];

export const VENDOR_PRESETS: PresetTemplate[] = [
  {
    item_name: "Factory Modular Supply",
    category: "vendor_supply",
    cost_basis: "vendor_quote",
    unit_rate: 0,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
  {
    item_name: "Hybrid: Factory Shutter + Site Carcass",
    category: "vendor_supply",
    cost_basis: "vendor_quote",
    unit_rate: 0,
    margin_percentage: 25,
    wastage_percentage: 0,
    include_in_client_price: true,
  },
];
